### ISSUE TITLE
Have to run make twice

### ISSUE THREAD

**Issue by ingvarha** [lkarsten/libvmod-tcp#1]
On el6, I have to run make twice to make vmod-tcp to compile. The first run dies at

make[2]: **\* No rule to make target `vcc_if.lo', needed by`libvmod_tcp.la'.  Stop.

Running make again works.

This problem is not visible on el7 or the fedoras.

Ingvar

**Comment by lkarsten** [comment]
Overtaken by events. This module has been merged into varnish-modules.

Build system configuration is differnt there and I believe this error is not present there. 
If you can reproduce it on varnish-modules, please reopen a new issue there.
